version: "3"
services:
  icecast:
    environment:
      - ICECAST_ADMIN_PASSWORD
      - ICECAST_PASSWORD
      - ICECAST_RELAY_PASSWORD
      - ICECAST_SOURCE_PASSWORD
    image: moul/icecast:latest
    ports:
      - 8000:8000
    volumes:
      - /etc/localtime:/etc/localtime:ro
  liquidsoap:
    environment:
      - ICECAST_HOST=icecast
      - ICECAST_PORT=8000
      - ICECAST_SOURCE_PASSWORD
    command: liquidsoap -v --debug /liquidsoap/liquidsoap.liq
    image: moul/liquidsoap:latest
    ports:
      - 8800:8800
    user: liquidsoap
    volumes:
      - ${LIQUIDSOAP_CONFIG}:/liquidsoap/liquidsoap.liq
      - ${LIQUIDSOAP_DATA}:/data
      - /etc/localtime:/etc/localtime:ro
